spring:
  cloud:
    gateway:
      routes:
        - id: data
          uri: http://localhost:8090
          predicates:
            - Path=/temperature/**,/humidity/**,/device/**
          filters:
            - UserFilterFactory
        - id: user
          uri: http://localhost:8090
          predicates:
            - Path=/user/login