spring:
  cloud:
    gateway:
      routes:
        - id: data
          uri: http://localhost:8090
          predicates:
            - Path=/humidity/{deviceId}/latest,/temperature/{deviceId}/latest
          filters:
            - UserFilterFactory
            - UserDeviceAccessFilterFactory
        - id: login
          uri: http://localhost:8090
          predicates:
            - Path=/user/login
        - id: userDevices
          uri: http://localhost:8090
          predicates:
            - Path=/device/user
          filters:
            - UserFilterFactory
            - UserUrlFilterFactory